In [ ]:
import numpy as np
#l1 = [1, 2, 3,"akmal",True] converts everything to string 
l1 = [1, 2, 3,]
l2 = [4, 5, 6]
a1 = np.array(l1)
a2 = np.array([l1, l2])
print(a1)
#print(a2)
print(a2.shape)


[1 2 3]
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a2.reshape(3,2) #no of elements should be same

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a2[: ,1:]

array([[2, 3],
       [5, 6]])

In [27]:
arr = np.arange(1, 10,2)
#arr
arr2 = np.linspace(2, 5, 5)
print(arr, arr2)
arr2

[1 3 5 7 9] [2.   2.75 3.5  4.25 5.  ]


array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [ ]:
#copy and broadcasting works with refrencing
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[4:] = 20
arr1 = arr # arr.copy() to avoid referencing
print(arr, arr1)
arr1[5:] = 30
print(arr, arr1)

[ 1  2  3  4 20 20 20 20 20] [ 1  2  3  4 20 20 20 20 20]
[ 1  2  3  4 20 30 30 30 30] [ 1  2  3  4 20 30 30 30 30]


In [ ]:
np.random.rand(2,3) * 10
#between 0 and 1

array([[4.97258268, 2.21449129, 5.40339474],
       [6.4878894 , 4.5073974 , 8.78489955]])

In [44]:
np.random.randn(2,3)  #from normal distribution centered at 0 with std of 1

array([[-0.69041661,  1.20050547,  0.82270097],
       [ 1.21378715,  0.44646995,  0.52451679]])

In [45]:
np.random.randint(1,10, (2,3)) #between 1 and 10

array([[9, 4, 9],
       [3, 5, 6]], dtype=int32)

In [46]:
np.random.random_sample((2,3)) #float between 0 and 1

array([[0.87871692, 0.41011801, 0.52819565],
       [0.72713962, 0.32105928, 0.02102116]])