In [3]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A[1,2]) # 2nd row 3rd column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [ ]:
B = np.arange(12) #this gives an array of numbers from 0 to 11
B = B.reshape(3,4) # this reshapes that array into 3 rows and 4 columns
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
