In [4]:
# tensors are just arrays with higher dimension than matrices but matrices can also be said order 2 tensors 

# writing an array as order 3 tensor

import numpy as np

t = np.array([1,2,3,4]).reshape((1,1,4,1)) # thiss is tensor fo order 4 

print(t)

[[[[1]
   [2]
   [3]
   [4]]]]


In [5]:
# scalar as a tensor

t = np.array(42).reshape((1,1,1,1))

print(t)

[[[[42]]]]


In [11]:
a = np.array([[1, 2, 3],
				[4, 5, 6]])
c = np.array([10, 20, 30])

print("a:")
print(a)
print("c:", c)

print("c * a:")
print(c * a)

print("a * c:")
print(a * c)

print("a / c:")
print(a / c)

print("c / a :",c / a)
# print(c / a)

print("a ** 2:")
print(a ** 2)


a:
[[1 2 3]
 [4 5 6]]
c: [10 20 30]
c * a:
[[ 10  40  90]
 [ 40 100 180]]
a * c:
[[ 10  40  90]
 [ 40 100 180]]
a / c:
[[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]
c / a : [[10.  10.  10. ]
 [ 2.5  4.   5. ]]
a ** 2:
[[ 1  4  9]
 [16 25 36]]


In [12]:
#broadcasting a 2 component vector over 2x3 matrix

d = np.array([10,11])
d = d.reshape((2,1))
print(d)
print(a+d)

[[10]
 [11]]
[[11 12 13]
 [15 16 17]]
