In [10]:
import numpy as np

x = np.array([1, 2, 3, 4, 5]) # a row vector
y = np.array([[1], [2], [3], [4], [5]]) # a column vector

print("Row vector x:")
print(x)
print("\nColumn vector y:")
print(y)


Row vector x:
[1 2 3 4 5]

Column vector y:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [11]:
#converting row vector to column vector 
z = x.reshape(5,1)
print(z)


[[1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
#unit vector
u = x/np.sqrt((x*x).sum())
print(x)
print(u)

[1 2 3 4 5]
[0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]


In [18]:
#vector transpose
# print(x.reshape((5,1)))

v = np.array([1,2,3])
v = v.reshape((3,1)) # as transpose does not work on 1D arrays, we need to convert it to 2D array first or say we are increasing order of tensor from 1 to 2

print(v)

print(v.transpose())

print(v.T)

[[1]
 [2]
 [3]]
[[1 2 3]]
[[1 2 3]]


In [19]:
#inner product of two vectors
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a, b)
d = (a*b).sum() # another way to calculate inner product
print(c)
print(d)


32
32


In [21]:
#angle between two vectors
A = np.sqrt((a*a).sum())
B = np.sqrt((b*b).sum())

theta = np.arccos(c/(A*B)) # this is in radians, to convert it to degrees we can use np.degrees(theta)
print(theta)
print(np.degrees(theta))

0.2257261285527342
12.933154491899135
