In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5]) # a row vector
y = np.array([[1], [2], [3], [4], [5]]) # a column vector

print("Row vector x:")
print(x)
print("\nColumn vector y:")
print(y)


Row vector x:
[1 2 3 4 5]

Column vector y:
[[1]
 [2]
 [3]
 [4]
 [5]]


In [6]:
#converting row vector to column vector 
z = x.reshape(5,1)
print(z)


[[1]
 [2]
 [3]
 [4]
 [5]]
